MI and Entropy examples for multidimensional variables
brainets/hoi pull request #54
Opened 2024-07-18 17:23 UTC by chrisferreyra13

Thanks for contributing a pull request!

Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value
all user contributions, no matter how minor they are. If we are slow to
review, either the pull request needs some benchmarking, tinkering,
convincing, etc. or more likely the reviewers are simply busy. In either
case, we ask for your understanding during the review process.

Again, thanks for contributing!

#### Reference issue
None, new examples.

#### What does this implement/fix?
This PR has two new example scripts in which a comparison between MI/Entropy estimators is shown using gaussian variables with multiple dimensions.

#### Additional information
Kernel estimator should be added to MI example after following fix.

2024-07-31 10:00 UTC, chrisferreyra13 commented
Hey sorry, github automatically included my new change for entropy/mi knn in this PR. Let me know if I remove it.

2024-07-31 11:57 UTC, EtienneCmb requested changes
Hey @chrisferreyra13,

Thanks for the PR. I made several comments, most of them involve minor changes.

Best,

2024-07-31 11:57 UTC, EtienneCmb commented on .vscode/launch.json
Please remove this file. You can add it to the .gitignore `.vscode/*`

2024-07-31 11:57 UTC, EtienneCmb commented on hoi/core/entropies.py
@chrisferreyra13 I guess it's faster because you use broadcasting rules. Can you check that it doesn't consume to much RAM when using a larger number of nodes? Same question for the mi

2024-07-31 11:57 UTC, EtienneCmb commented on hoi/core/entropies.py
Also, you've checked that both implementations give the exact same results?

2024-08-04 15:43 UTC, chrisferreyra13 commented on .vscode/launch.json
Sorry! I didn't realize it was included.

2024-08-04 16:02 UTC, chrisferreyra13 commented on hoi/core/entropies.py
Yes exactly. The motivation originated because for >5k samples, the method started to become really slow.

I try to measure peak memory consumption with tracemalloc pkg using get_traced_memory function. I don't trust my results hahaha 😅 because for me the new method should consume more memory for sure! Do you know another way to measure memory? I attach the corresponding plots.
I am following this approach (similarly for total info)
```
for nf in n_features:
    x = np.random.rand(n_samples, nf)
    # inject redundancy between nodes (0, 1, 2)
    x[:, 1] += x[:, 0]
    x[:, 2] += x[:, 0]
    model = TC(x)
    
    tracemalloc.start()
    model.fit(method="knn_old", minsize=3, maxsize=nf)
    mem_usg_knn_old.append(tracemalloc.get_traced_memory()[1]/1024**2)
    tracemalloc.stop()
```
![image](https://github.com/user-attachments/assets/dd88e9e6-47b3-428a-b594-c46f17a59868)
![image](https://github.com/user-attachments/assets/00c41abf-c923-44a4-afa0-4f14052af57e)


I also measure if they give the same results. They do, but when I check by eye the values the last decimals are not the same. I guess this is only a matter of numerical precision of the functions used. I attach plots.

![image](https://github.com/user-attachments/assets/549fdad6-f2b3-4a29-a0d2-7de521ac1d20)
![image](https://github.com/user-attachments/assets/568225e2-b352-4d3f-bac4-32d40c477c84)


If the method is heavy in practice, we can leave an option for slow/fast method. Although to do I expect people using HOI in a cluster for real analysis, where RAM should be ok.

Let me know!

2024-08-30 11:51 UTC, merged

2024-08-30 11:52 UTC, EtienneCmb commented
Thank you @chrisferreyra13, indeed, it's surprising that the new method doesn't use more memory. I merged your modifications. In case we/you/someone find memory issues in the future, we can go back to this PR. Best,